const groceryItems = [
  {
    id: 1,
    name: "Tomatoes",
    price: 45,
    hasDiscount: true,
    discountPrice: 35,
    marketplaceName: "Blackrock PLC",
    category: "Vegetables",
    mainCategory: "Vegetables",
    subCategory: "Red Vegetables",
    image: '/img/data/tomato.avif',
    inStock: true,
    unit: "kg",
    rating: 5,
    distanceKm: 2.1
  },
  {
    id: 2,
    name: "Bananas",
    price: 30,
    hasDiscount: false,
    discountPrice: null,
    marketplaceName: "Fresh Farms Ltd.",
    category: "Fruits",
    mainCategory: "Fruits",
    subCategory: "Tropical Fruits",
    image: '/img/data/banana.jpg',
    inStock: true,
    unit: "dozen",
    rating: 4,
    distanceKm: 3.4
  },
  {
    id: 3,
    name: "Red Onions",
    price: 50,
    hasDiscount: true,
    discountPrice: 40,
    marketplaceName: "Gulit Wholesale",
    category: "Vegetables",
    mainCategory: "Vegetables",
    subCategory: "Bulb Vegetables",
    image: '/img/data/ONIONS.jpg',
    inStock: false,
    unit: "kg",
    rating: 5,
    distanceKm: 1.8
  },
  {
    id: 4,
    name: "Bottled Honey",
    price: 120,
    hasDiscount: false,
    discountPrice: null,
    marketplaceName: "BeePure Ethiopia",
    category: "Pantry",
    mainCategory: "Pantry",
    subCategory: "Sweeteners",
    image: '/img/data/honey.jpg',
    inStock: true,
    unit: "bottle",
    rating: 5,
    distanceKm: 2.9
  },
  {
    id: 5,
    name: "Avocados",
    price: 55,
    hasDiscount: true,
    discountPrice: 45,
    marketplaceName: "Green Basket",
    category: "Fruits",
    mainCategory: "Fruits",
    subCategory: "Oily Fruits",
    image: '/img/data/avocado.jpg',
    inStock: true,
    unit: "kg",
    rating: 5,
    distanceKm: 2.5
  },
  {
    id: 6,
    name: "Whole Milk",
    price: 38,
    hasDiscount: false,
    discountPrice: null,
    marketplaceName: "EthioDairy Co.",
    category: "Dairy",
    mainCategory: "Dairy",
    subCategory: "Milk",
    image: '/img/data/milk.jpg',
    inStock: true,
    unit: "liter",
    rating: 4,
    distanceKm: 4.0
  },
  {
    id: 7,
    name: "Brown Eggs",
    price: 65,
    hasDiscount: true,
    discountPrice: 55,
    marketplaceName: "Gulit Fresh",
    category: "Dairy",
    mainCategory: "Dairy",
    subCategory: "Eggs",
    image: '/img/data/brownEgg.jpg',
    inStock: true,
    unit: "dozen",
    rating: 4,
    distanceKm: 1.6
  },
  {
    id: 8,
    name: "Green Peppers",
    price: 25,
    hasDiscount: false,
    discountPrice: null,
    marketplaceName: "Blackrock PLC",
    category: "Vegetables",
    mainCategory: "Vegetables",
    subCategory: "Green Vegetables",
    image: '/img/data/pepper.jpg',
    inStock: true,
    unit: "kg",
    rating: 3,
    distanceKm: 3.3
  },
  {
    id: 9,
    name: "Teff Flour",
    price: 80,
    hasDiscount: true,
    discountPrice: 70,
    marketplaceName: "YegnaGrains",
    category: "Pantry",
    mainCategory: "Pantry",
    subCategory: "Grains & Flour",
    image: '/img/data/teff.jpg',
    inStock: true,
    unit: "kg",
    rating: 5,
    distanceKm: 2.0
  },
  {
    id: 10,
    name: "Lemons",
    price: 25,
    hasDiscount: false,
    discountPrice: null,
    marketplaceName: "LimeMarket",
    category: "Fruits",
    mainCategory: "Fruits",
    subCategory: "Citrus Fruits",
    image: '/img/data/lemon.jpg',
    inStock: true,
    unit: "kg",
    rating: 4,
    distanceKm: 2.7
  },
  {
    id: 11,
    name: "Injera (10 pcs)",
    price: 45,
    hasDiscount: false,
    discountPrice: null,
    marketplaceName: "InjeraHome",
    category: "Pantry",
    mainCategory: "Pantry",
    subCategory: "Ready to Eat",
    image: '/img/data/injera.jpg',
    inStock: true,
    unit: "pack",
    rating: 5,
    distanceKm: 1.9
  },
  {
    id: 12,
    name: "Green Beans",
    price: 33,
    hasDiscount: true,
    discountPrice: 28,
    marketplaceName: "Gulit Wholesale",
    category: "Vegetables",
    mainCategory: "Vegetables",
    subCategory: "Green Vegetables",
    image: '/img/data/beans.webp',
    inStock: true,
    unit: "kg",
    rating: 4,
    distanceKm: 2.6
  },
  {
    id: 13,
    name: "Apples",
    price: 60,
    hasDiscount: false,
    discountPrice: null,
    marketplaceName: "Highland Fruits",
    category: "Fruits",
    mainCategory: "Fruits",
    subCategory: "Temperate Fruits",
    image: '/img/data/apple.jpg',
    inStock: true,
    unit: "kg",
    rating: 5,
    distanceKm: 3.8
  },
  {
    id: 14,
    name: "Carrots",
    price: 35,
    hasDiscount: false,
    discountPrice: null,
    marketplaceName: "Blackrock PLC",
    category: "Vegetables",
    mainCategory: "Vegetables",
    subCategory: "Root Vegetables",
    image: '/img/data/carrot.jpg',
    inStock: true,
    unit: "kg",
    rating: 4,
    distanceKm: 2.2
  },
  {
    id: 15,
    name: "Coffee Beans",
    price: 150,
    hasDiscount: true,
    discountPrice: 135,
    marketplaceName: "Ethiopia Coffee Hub",
    category: "Beverages",
    mainCategory: "Beverages",
    subCategory: "Coffee",
    image: '/img/data/coffee.jpg',
    inStock: true,
    unit: "500g",
    rating: 5,
    distanceKm: 3.0
  },
  {
    id: 16,
    name: "Bottled Water",
    price: 15,
    hasDiscount: false,
    discountPrice: null,
    marketplaceName: "AquaPlus",
    category: "Beverages",
    mainCategory: "Beverages",
    subCategory: "Water",
    image: '/img/data/water.jpg',
    inStock: true,
    unit: "liter",
    rating: 3,
    distanceKm: 2.4
  },
  {
    id: 17,
    name: "Holland Yogurt",
    price: 25,
    hasDiscount: false,
    discountPrice: null,
    marketplaceName: "EthioDairy Co.",
    category: "Dairy",
    mainCategory: "Dairy",
    subCategory: "Yogurt",
    image: '/img/data/holland.jpg',
    inStock: true,
    unit: "cup",
    rating: 4,
    distanceKm: 3.6
  },
  {
    id: 18,
    name: "Pasta",
    price: 35,
    hasDiscount: true,
    discountPrice: 30,
    marketplaceName: "FastPantry",
    category: "Pantry",
    mainCategory: "Pantry",
    subCategory: "Dry Goods",
    image: '/img/data/pasta.avif',
    inStock: true,
    unit: "pack",
    rating: 4,
    distanceKm: 2.3
  },
  {
    id: 19,
    name: "Cabbage",
    price: 28,
    hasDiscount: false,
    discountPrice: null,
    marketplaceName: "Green Basket",
    category: "Vegetables",
    mainCategory: "Vegetables",
    subCategory: "Leafy Vegetables",
    image: '/img/data/cabbege.webp',
    inStock: true,
    unit: "kg",
    rating: 4,
    distanceKm: 1.7
  },
  {
    id: 20,
    name: "Oranges",
    price: 50,
    hasDiscount: true,
    discountPrice: 40,
    marketplaceName: "Fresh Farms Ltd.",
    category: "Fruits",
    mainCategory: "Fruits",
    subCategory: "Citrus Fruits",
    image: '/img/data/orange.avif',
    inStock: true,
    unit: "kg",
    rating: 5,
    distanceKm: 2.8
  }
];

export default groceryItems;
